# Generated by Django 2.1.7 on 2019-03-23 02:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_category_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ckeditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
